name: newsapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:

  flutter_native_splash: ^2.0.0

  flutter_launcher_icons: ^0.13.1

  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png

flutter_native_splash:
  image: "lib/assets/jornal.png"
  color: "#42a5f5"
  android: true
  ios: true

flutter_icons:
    image_path: "lib/assets/jornal.png"
    android: true
    ios: true
